on:
  push:
    branches:
      - main


jobs:
  update-parent-module:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          repository: 'MPZinke/SmartCurtain'
          token: '${{ secrets.SMARTCURTAIN_RW_TOKEN }}'
          submodules: 'true'

      - name: "Update Parent"
        run: |
          git submodule update --remote
          git commit -am "Updates to track HEAD of SmartCurtain-Backend"
          git push
